# Handling Duplicate Data

In [1]:
import pandas as pd

In [2]:
data = {"name":["a","b","c","d","a","c"],"eng":[8,7,5,8,8,4],"hindi":[2,3,4,5,2,6]}

In [3]:
df  = pd.DataFrame(data)
df
# when whole row is duplicate then data is called duplicate of another if there is only two columns are same but whole row is  not same so then they are not dupplicate.

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    4      6

In [4]:
# duplicated()  : it is a function use find duplicates , true if duplicate exit false if no .

# df["Duplicates"] = df.duplicated()
# df

Remove duplicate Data

In [5]:
# Use drop_duplicates() : fxn for removing duplicates

# keep : parameter used to take which duplicate we want

# inplace parameter : not to create new change in the same dataset.

df.drop_duplicates(keep="first",inplace=True,)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    4      6

# Removing Duplicates from Large Datasets.

In [6]:
dataset = pd.read_csv("loan.csv")
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,NaN,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,NaN,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [7]:
dataset.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
609    False
610    False
611    False
612    False
613    False
Length: 614, dtype: bool

In [8]:
dataset.shape

(614, 13)

In [9]:
dataset.drop_duplicates(inplace=True)

In [10]:
dataset.shape
# there was no duplicates

(614, 13)